// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class AnimalTemplate
    : EntityBase
{

    public string Name { get; set; }

    public string Species { get; set; }
    public string Status { get; set; }
    public string Notes { get; set; }

    public virtual ICollection<FarmingBatch> FarmingBatches { get; set; } = new List<FarmingBatch>();

    public virtual ICollection<GrowthStageTemplate> GrowthStageTemplates { get; set; } = new List<GrowthStageTemplate>();

    public virtual ICollection<VaccineTemplate> VaccineTemplates { get; set; } = new List<VaccineTemplate>();
}