// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class AnimalSale : EntityBase
{

    public Guid FarmingBatchId { get; set; }

    public DateTime? SaleDate { get; set; }

    public double Revenue { get; set; }

    public string BuyerInfo { get; set; }

    public virtual FarmingBatch FarmingBatch { get; set; }
}