// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class CageStaff
{
    public Guid CageStaffId { get; set; }

    public Guid CageId { get; set; }

    public Guid StaffFarmId { get; set; }

    public DateTime? AssignedDate { get; set; }

    public virtual Cage Cage { get; set; }

    public virtual User StaffFarm { get; set; }
}