// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class ControlBoard
{
    public Guid ControlBoardId { get; set; }

    public Guid CageId { get; set; }

    public Guid ControlBoardTypeId { get; set; }

    public string ControlBoardCode { get; set; }

    public string Name { get; set; }

    public int PinCode { get; set; }

    public bool Status { get; set; }

    public bool State { get; set; }

    public string CommandOn { get; set; }

    public string CommandOff { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Cage Cage { get; set; }

    public virtual ControlBoardType ControlBoardType { get; set; }

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}