// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class DailyFoodUsageLog : EntityBase
{
    public Guid StageId { get; set; }

    public decimal? RecommendedWeight { get; set; }

    public decimal? ActualWeight { get; set; }

    public string Notes { get; set; }

    public DateTime? LogTime { get; set; }

    public string Photo { get; set; }

    public int? TaskId { get; set; }

    public virtual GrowthStage Stage { get; set; }
}