// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class FarmSubscription
{
    public Guid SubscriptionId { get; set; }

    public Guid FarmId { get; set; }

    public Guid PlanId { get; set; }

    public Guid UserId { get; set; }

    public int NumberOfUsers { get; set; }

    public bool? RequiresVet { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public decimal TotalCost { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Farm Farm { get; set; }

    public virtual SubscriptionPlan Plan { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual User User { get; set; }
}