// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class FarmAdmin
{
    public Guid FarmAdminId { get; set; }

    public Guid FarmId { get; set; }

    public Guid AdminId { get; set; }

    public DateTime? AssignedDate { get; set; }

    public virtual User Admin { get; set; }

    public virtual Farm Farm { get; set; }
}