// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class FoodTemplate : EntityBase
{

    public Guid StageTemplateId { get; set; }

    public string FoodName { get; set; }

    public decimal? RecommendedWeightPerSession { get; set; }

    public decimal? WeightBasedOnBodyMass { get; set; }

    public virtual GrowthStageTemplate StageTemplate { get; set; }
}