// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class GrowthStageTemplate : EntityBase
{

    public Guid TemplateId { get; set; }

    public string StageName { get; set; }

    public decimal? WeightAnimal { get; set; }

    public int? AgeStart { get; set; }

    public int? AgeEnd { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<FoodTemplate> FoodTemplates { get; set; } = new List<FoodTemplate>();
    public ICollection<TaskDailyTemplate> TaskDailyTemplates { get; set; } = new List<TaskDailyTemplate>();

    public virtual AnimalTemplate Template { get; set; }
}