// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class HealthLog : EntityBase
{

    public Guid PrescriptionId { get; set; }

    public DateTime? Date { get; set; }

    public string Notes { get; set; }

    public string Photo { get; set; }

    public Guid? TaskId { get; set; }

    public virtual Prescription Prescription { get; set; }
}