// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class Job : EntityBase
{

    public Guid ScheduleId { get; set; }

    public Guid ControlBoardId { get; set; }

    public Guid SensorId { get; set; }

    public Guid JobTypeId { get; set; }
    public Guid? ControlId { get; set; }

    public string JobCode { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool StateSmaller { get; set; }

    public double? ValueSmaller { get; set; }

    public double? ValueLarger { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ControlBoard ControlBoard { get; set; }

    public virtual ICollection<JobLog> JobLogs { get; set; } = new List<JobLog>();

    public virtual JobType JobType { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual Sensor Sensor { get; set; }
    public virtual ControlDevice ControlDevice { get; set; }
}