// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class Notification : EntityBase
{

    public Guid UserId { get; set; }

    public Guid NotiTypeId { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsRead { get; set; }

    public int? FarmId { get; set; }

    public int? CageId { get; set; }

    public virtual NotificationType NotiType { get; set; }

    public virtual User User { get; set; }
}