// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class NotificationType : EntityBase
{

    public string NotiTypeName { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}