// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class Role : EntityBase
{

    public string RoleName { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}