// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class Schedule : EntityBase
{

    public string ScheduleCode { get; set; }

    public string Name { get; set; }

    public string TimeOn { get; set; }

    public string TimeOff { get; set; }

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}