// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class Sensor : EntityBase
{

    public Guid SensorTypeId { get; set; }

    public Guid CageId { get; set; }

    public string SensorCode { get; set; }

    public string Name { get; set; }

    public int PinCode { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int NodeId { get; set; }

    public virtual Cage Cage { get; set; }

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    public virtual ICollection<SensorDataLog> SensorDataLogs { get; set; } = new List<SensorDataLog>();

    public virtual SensorType SensorType { get; set; }
}