// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class StatusLog : EntityBase
{

    public Guid TaskId { get; set; }

    public Guid StatusId { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Status Status { get; set; }

    public virtual Task Task { get; set; }
}