// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class Status : EntityBase
{

    public string StatusName { get; set; }

    public virtual ICollection<StatusLog> StatusLogs { get; set; } = new List<StatusLog>();
}