// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class StockLog : EntityBase
{

    public Guid StackId { get; set; }

    public string FoodType { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? CostPerKg { get; set; }

    public DateOnly DateAdded { get; set; }

    public virtual FoodStack Stack { get; set; }

}