// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class SubscriptionPlan
{
    public Guid PlanId { get; set; }

    public string PlanName { get; set; }

    public decimal CostPerUser { get; set; }

    public decimal CostPerVet { get; set; }

    public decimal MonthlyBaseCost { get; set; }

    public virtual ICollection<FarmSubscription> FarmSubscriptions { get; set; } = new List<FarmSubscription>();
}