// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class TaskType : EntityBase
{

    public string TaskTypeName { get; set; }

    public int? PriorityNum { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}