// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class User : EntityBase
{

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid RoleId { get; set; }

    public virtual ICollection<CageStaff> CageStaffs { get; set; } = new List<CageStaff>();

    public virtual ICollection<FarmAdmin> FarmAdmins { get; set; } = new List<FarmAdmin>();

    public virtual ICollection<FarmSubscription> FarmSubscriptions { get; set; } = new List<FarmSubscription>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}