// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class VaccineScheduleLog
{
    public Guid VaccineScheduleLogId { get; set; }

    public Guid ScheduleId { get; set; }

    public DateOnly? Date { get; set; }

    public string Notes { get; set; }

    public string Photo { get; set; }

    public int? TaskId { get; set; }

    public virtual VaccineSchedule Schedule { get; set; }
}