// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartFarmManager.DataAccessObject.Models;

public partial class Vaccine : EntityBase
{

    public string Name { get; set; }

    public string Method { get; set; }

    public int? AgeStart { get; set; }

    public int? AgeEnd { get; set; }

    public virtual ICollection<VaccineSchedule> VaccineSchedules { get; set; } = new List<VaccineSchedule>();
}